### ISSUE TITLE
Can you show us a much more detailful vignette from 10X datasets?

### ISSUE THREAD

**Issue by pangxueyu233** [rajewsky-lab/novosparc#10]

**Comment by pangxueyu233** [comment]
It's really an impressive study!!!  And I really want to use this powerful weapen in my study.
Firstly, in your reconstruct_tissue.py scripts. I cannot make sure the dge.txt meaning that a count table including cells expression information with hvgs as rownames or a count table including cells expressing information with top markers in each cell subtypes as rownames. 

Secondly, in your packages 
there is no 'novosparc.rc.construct_target_grid' formula because I got the error like that:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'novosparc.reconstruction' has no attribute 'construct_target_grid'
```
Could you help me work it out?
Thanks

**Comment by pangxueyu233** [comment]
I Find your construct_target_grid formula, it's in novosparc.geometry, and I tried to move on by using the counts table including cells expression information with hvgs as rownames

**Comment by Eddylyf** [comment]
Hi Pangxueyu233,
I also got the same error 
"AttributeError: module 'novosparc.reconstruction' has no attribute 'construct_target_grid'"
I saw your answer but still do not clear how to make it work, may I ask you what should I do with the could you please help me resolve this issue?
Thanks so much!
Best,
Yanfang

**Comment by pangxueyu233** [comment]
@Eddylyf Hi,
I find the formula in 'novosparc.geometry' module. And you just tried codes as following:
```
locations = novosparc.geometry.construct_target_grid(num_cells)
```
And that will help you to fix it up. But I still meet so many errors in the later processing, I think maybe developers need to give us a much more detail vignette and that will finally help.
And if you have worked it out, please show me what the results you have got.

**Comment by Eddylyf** [comment]
Hi @pangxueyu233 , 
Thanks so much for your great help! I will try it again with my dataset, indeed I also think author should give us a more detail code. Thanks again!
Best,
Yanfang

**Comment by nukappa** [comment]
We're working on updating the vignettes and also on facilitating the construction of the tissue grids, in a couple of days we'll push those to the repo

**Comment by pangxueyu233** [comment]
@nukappa  
That would be very nice.
Appreciated for your working, and we are waiting for your new version.

**Comment by matq007** [comment]
Hey @nukappa, any update on the `reconstruct_tissue.py`?

**Comment by nukappa** [comment]
@matq007 @pangxueyu233 I just pushed a [tutorial](https://github.com/rajewsky-lab/novosparc/blob/master/reconstruct_drosophila_embryo_tutorial.ipynb) on reconstructing the Drosophila embryo.
