### ISSUE TITLE
Different grids shapes and spatially informative genes

### ISSUE THREAD

**Issue by arielmadr** [rajewsky-lab/novosparc#11]
Hi, 

Thank you for the fantastic package. I've used the reconstruct_tissue.py script with my data and the results look promising. However, I have a couple of questions:

1) I was wondering, do you have any suggestions in how to use different shapes for the grids ( like circles or elipses)? 
2) Do you have any function in the package to use for identify spatially informative genes? I couldn't find it. 

Thanks a lot!

Ariel

**Comment by nukappa** [comment]
Hi, thanks for your feedback, much appreciated!

1. I just pushed version 0.3.9 which contains a function that can be used for custom target spaces, see also the docs for more details.
2. This is still in the pipeline, shouldn't take longer to appear.

Nikos

**Comment by enessenel** [comment]
Algorithm to identify spatially informative genes is implemented now in 7bf55f986ca1ef213a89c04813969a38c30ad2b5 and available with the version 0.3.10.
