### ISSUE TITLE
How to calculate D(exp, phys)?

### ISSUE THREAD

**Issue by ChengxiangQiu** [rajewsky-lab/novosparc#15]
Hi,
Thanks for providing such an amazing tool used for spatial analysis.

Now I have a reference atlas from ISH, but it's binary for each gene (1 means the given gene expresses in the bin, and 0 means not). 
(1) How should I calculate the D(exp, phys)? I found that in the example, cost_marker_genes matrix is calculated by cdist(), but in that case, the exp and phys have same scale and distribution. For my case, exp is normalized expression value from RNA-seq reads, and phys is binary value. How can I calculate the D(exp, phys)? should I do some normalization first?
(2) How to select value for alpha_linear? or it's a hyper parameter, I need to try myself?

Thank you!
Chengxiang

**Comment by nukappa** [comment]
Hi,
(1) you can go ahead and calculate D(exp, phys) with your binary reference atlas. In our experience, continuous values result in better reconstructions, but a binary atlas already helps a lot. Check afterwards if your cells mapped to the regions you instructed them to.
(2) when using a reference atlas, alpha_linear=1 will only map with the marker genes. When mapping de novo, set it to 0. Intermediate values will consider both constructs. We mostly use alpha_linear=0.5, unless if we feel the target space doesn't reflect biological truth. In that case we use higher values of alpha.
