### ISSUE TITLE
geometry.txt

### ISSUE THREAD

**Issue by grst** [rajewsky-lab/novosparc#19]
Hi @nukappa, 

I am a bit confused with the geometry file. 

I could only find this one: 
https://github.com/rajewsky-lab/novosparc/blob/master/novosparc/datasets/bdtnp/geometry.txt

It has 6079 lines and fails with the *in-situ* data. 
The one you have in the tutorial notebook looks a bit different, and, I assume, has 3039 lines. 

`geometry.txt` from repo: 
![image](https://user-images.githubusercontent.com/7051479/72518020-b434f800-3854-11ea-81d8-a6b4a3c490f1.png)

geometry in the tutorial notebook: 
![image](https://user-images.githubusercontent.com/7051479/72518051-c2831400-3854-11ea-8911-f32c947354a3.png)

Could you please provide the right one? Or am I overlooking sth? 

Cheers, 
Gregor

**Comment by nukappa** [comment]
Hi @grst that's the correct file, containing 3039*2 locations in (x, y, z).
For the tutorial (and also the figures in the paper) truncate it to the first 3039 locations in (x, z).
The embryo has a bilateral symmetry at this stage, so only half of locations have unique transcriptomes.

**Comment by grst** [comment]
That has worked, thanks! 
I can now reproduce all the figures.
