### ISSUE TITLE
nc.rc.setup_for_OT_reconstruction

### ISSUE THREAD

**Issue by kzxkzx** [rajewsky-lab/novosparc#20]
sorry,when I run nc.rc.setup_for_OT_reconstruction,I always meet one issue:RuntimeWarning: invalid value encountered in true_divide cost_locations = sp_locations / sp_locations.max(),and then in calculating the GW matrix,it comes that It.  |Err         
-------------------
    0|     nan|.

**Comment by enessenel** [comment]
do you use a geometry from the example script or do you have your own? if you do have your own, in which format is it?
