### ISSUE TITLE
The object hold Moran’s score

### ISSUE THREAD

**Issue by I-Hao** [rajewsky-lab/novosparc#22]
Hi,
Thank you for providing this powerful tool.
In applying this tool to my data, I have problems in identifying the objects holding the data I’m looking for, could you help me to identify them?
 1. Which object holds Moran’s score?
2. Which object holds the p-value for each gene?
3. Which object holds the coordinate of the input cells in the reconstructed space?

Thank you for your help, really appreciate it.
I-Hao

**Comment by nukappa** [comment]
hi, thanks for the comments, we're soon pushing a version containing this, we just got stuck in a some dependencies problems.

**Comment by enessenel** [comment]
Hi,
we have pushed the version 0.3.10 with 7bf55f986ca1ef213a89c04813969a38c30ad2b5 where Moran's I is implemented.
1-2) You can run the algorithm with the morans function package. This will return a list of informative genes and save the morans score and p-values to a file morans.txt
3) you can use the gw matrix object to check the mapped locations of the cells (there is also a function called plot_mapped_cells() to plot the mappings)
