### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ccruizm** [rajewsky-lab/novosparc#25]
Good day,

I want to test this wonderful tool. However, I am having  issues with the installation. I have created a new conda env with the required packages and got the following error:

```
ERROR: Command errored out with exit status 1:
     command: /hpc/pmc_stunnenberg/cruiz/miniconda3/envs/novosparc/bin/python3.5 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i7t40di6/rtree/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i7t40di6/rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-i7t40di6/rtree/pip-egg-info
         cwd: /tmp/pip-install-i7t40di6/rtree/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i7t40di6/rtree/setup.py", line 3, in <module>
        import rtree
      File "/tmp/pip-install-i7t40di6/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/tmp/pip-install-i7t40di6/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/tmp/pip-install-i7t40di6/rtree/rtree/core.py", line 143, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/hpc/pmc_stunnenberg/cruiz/miniconda3/envs/novosparc/lib/python3.5/ctypes/__init__.py", line 364, in __getattr__
        func = self.__getitem__(name)
      File "/hpc/pmc_stunnenberg/cruiz/miniconda3/envs/novosparc/lib/python3.5/ctypes/__init__.py", line 369, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /hpc/pmc_stunnenberg/cruiz/miniconda3/envs/novosparc/bin/python3.5: undefined symbol: Error_GetLastErrorNum
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I have tested it in two different HPC and both got the same error. What do you think the problem is?

Thanks in advance!

**Comment by nukappa** [comment]
Hi, thanks for bringing this to our attention, it seems like there's a dependency conflict between libraries from `pip` and `conda`. Could you try to install the dependencies with `conda` first? `pysal` in particular. We're in the process of wrapping `novosparc` also in conda, so that should fix those problems.

**Comment by ccruizm** [comment]
Thanks for your quick reply. I tried installing all dependencies first (including `pysal`) but still getting the same message error. Any other suggestion I can try?

**Comment by dgcha97** [comment]
Hi, I think I faced almost same problem, and I solved it by specifying the rtree version.
What if you try the command below?:
`pip install "rtree>=0.8,<0.9"`

**Comment by enessenel** [comment]
Hi Cristian, did installing rtree solved your problem?

**Comment by ccruizm** [comment]
Hello!

Effectively, specifying the `rtree` version allows a smooth installation! Thanks @dgcha97 for the suggestion 👍
