### ISSUE TITLE
ModuleNotFoundError: No module named 'pysal.explore.esda'

### ISSUE THREAD

**Issue by I-Hao** [rajewsky-lab/novosparc#28]
Hi,
I just installed the latest version of novosparc, but I have problems with loading it:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-4521efbc5556> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'inline')
      2 import numpy as np
----> 3 import novosparc as nc
      4 import matplotlib
      5 import matplotlib.pyplot as plt

~/opt/anaconda3/lib/python3.7/site-packages/novosparc/__init__.py in <module>
     15 from . import reconstruction as rc
     16 from . import geometry
---> 17 from . import analysis

~/opt/anaconda3/lib/python3.7/site-packages/novosparc/analysis/__init__.py in <module>
----> 1 from ._analysis import morans

~/opt/anaconda3/lib/python3.7/site-packages/novosparc/analysis/_analysis.py in <module>
      1 import numpy as np
      2 import pysal.lib
----> 3 from pysal.explore.esda.moran import Moran
      4 import time
      5 from multiprocessing import Pool

ModuleNotFoundError: No module named 'pysal.explore.esda'

my pysal version:
libpysal==4.2.2
pysal==2.2.0

Could you give me some hint? Thank you!

I-Hao

**Comment by enessenel** [comment]
Hi, 
Could you please try to install pysal version 2.1.0 and let me know if it works? In the meantime, i will check pysal version 2.2.0 as well.

**Comment by I-Hao** [comment]
Hi, installing the pysal version 2.1.0 works. Thanks!
