### ISSUE TITLE
Full environment and version

### ISSUE THREAD

**Issue by HichamAffia** [rajewsky-lab/novosparc#29]
Hi,

I'm testing novosparc, but I have trouble reproducing the outputs of the _reconstruct_drosophila_embryo_tutorial.ipynb_ tutorial. 

Here are the outputs I get for the denovo marker genes referenced tissue reconstruction.

![Novosparc_outputs](https://user-images.githubusercontent.com/37811366/75100871-c0257f80-55a1-11ea-9c52-e41584aa4a42.png)

I think it may be the versions of the dependencies installed automatically.
I'm in an virtual environment on linux CentOS 7, I tried using different novosparc releases with either Python 3.5 or 3.6 and made sure to have the modules versions recommended in the environments_and_versions.txt and requirements.txt files.

Could you kindly provide the full modules list with modules versions and the exact python version and novosparc release used successfully in the tutorial execution?

Thank you!

**Comment by I-Hao** [comment]
having a similar issue when applying the novosparc to my data, hoping they will answer this question.

**Comment by nukappa** [comment]
Hi, I doubt that the problem lies in the different releases or environments. We will need to double check the tutorial and write back.

**Comment by enessenel** [comment]
tutorial is updated with f651f2309732861625a79686618a71f393a8c359
