### ISSUE TITLE
How to plot two or more genes in the same time?

### ISSUE THREAD

**Issue by YiweiNiu** [rajewsky-lab/novosparc#31]
Hi,

Sorry to bother again.

I want to plot several genes at the same time, such as CD3G/CD3D for T cells, just like a "merged" FISH figure. Can I just average the value of these genes in `sdge` object to plot? Or there are some other caveats?

Many thanks!

**Comment by nukappa** [comment]
Hi, there's not a straightforward answer to this. Averaging the values of the two genes might be misleading if they are not expressed at similar levels. If you are only interested in binary expression (ON/OFF) you can extract this from the sdge by setting a threshold and then plot through a custom function. You'll need 4 colors for this: gene1_on, gene2_on, both genes on, both genes off.

If you need more quantitative information you should keep the continuous gene expression values and devise a similar plot.

Hope this helps.

**Comment by YiweiNiu** [comment]
Thank you for your reply! I would try as you suggested.
