### ISSUE TITLE
Create new spatial markes from ISH images

### ISSUE THREAD

**Issue by MalteMederacke** [rajewsky-lab/novosparc#35]
I am trying to apply your beautiful method to another system. I managed to set up the spatial reconstruction but now I want to implement new markes with the help of ISH images. Is there an implemented function to read out the data from image files? How do you create a marker table similar to  'bdtnp.txt' in your tutorial?

Best and many thanks for your work.

**Comment by nukappa** [comment]
Hi @MalteMederacke, we don't have a function in place for this, but the process of digitizing ISH images is similar to having different target geometries, [see also here](https://novosparc.readthedocs.io/tutorials.html#constructing-different-grid-shapes). If you have a few ISH images, you basically want to map them on your target space. Binary values are enough for start (0 or 1, meaning gene ON or gene OFF). You can next extend to 3 values (low, med, high) and so on.

**Comment by MalteMederacke** [comment]
Thank you so much for your answer.
