### ISSUE TITLE
/novosparc/plotting/_plotting.py

### ISSUE THREAD

**Issue by WhatAboutMyStar** [rajewsky-lab/novosparc#36]
line 148
plt.savefig(os.path.joint(folder, 'spatial_expression_intestine.png'))
should be plt.savefig(os.path.join(folder, 'spatial_expression_intestine.png'))

**Comment by WhatAboutMyStar** [comment]
or will get error when run the reconstruct_intestine_denovo.py

**Comment by enessenel** [comment]
thanks for noticing! it is fixed now
