### ISSUE TITLE
Downsampling of locations

### ISSUE THREAD

**Issue by MalteMederacke** [rajewsky-lab/novosparc#37]
Hi,
Thank you for you super great software!

I think if one intents of using the 'nc.geometry.create_target_space_from_image function', the downsampling in the  drosophila embryo tutorial is down incorrectly. 
It is currently this: locations = locations[np.random.choice(locations.shape[0], 3039), :]
but it should be with the option 'replace = False', because otherwise some locations will be sampled multiple times and the total number of cells used is smaller then 3039 or as intended. 

I suggest this:
locations = locations[np.random.choice(locations.shape[0],  num_cells, replace = False), :]

Another question: Do you think it is feasible to create a function which does this and generates a three dimensional target space? I did it manually for my purposes and the downstream analysis seems to work (as I understood, NovoSparC is capable of doing spatial reconstruction in 3 dimensions?); the bdtnp locations sheet is 3d aswell. How did you create a target space for example for the "seurat zebrafish embryo"?

**Comment by nukappa** [comment]
Hi, the latest commit fixed the issues with the tutorial.

The space for the zebrafish embryo is basically 2-dim, just a projection of a hemisphere.
novoSpaRc can work indeed with 3D spaces (or 1D, such as the examples we have) and we have tried this in the past with a few datasets. The problem there though is how to efficiently visualize the data and assess the different reconstructions.

**Comment by MalteMederacke** [comment]
Thank you for your comment. I just want to come back to the 3D spaces. Do you expect a difference in performance, when doing the reconstruction in 3D and just display/visualize the data in 2D? And would you suggest to increase the number of neighbors calculated setup_for_OT_reconstruction when working with a 3D target space?
