### ISSUE TITLE
Possibility to extract mapping information of cell to location in geometry?

### ISSUE THREAD

**Issue by Hsu-Che-Wei** [rajewsky-lab/novosparc#42]
Hi novosparc group,

I have successfully mapped my single cell data back to the geometry with average Pearson's r between prediction and ground truth being around 0.65. 

I wonder if there is a way to extract information of which cells in the single cell data is assigned/mapped to which location in the geometry.

It would be nice if you could provide some suggestion.

Thank you very much.  

Che-Wei

**Comment by nukappa** [comment]
Hi @Hsu-Che-Wei 

great that you're using novosparc. The information you're looking for is encoded in the GW matrix, just before the final spatial gene expression matrix. The GW matrix gives you the scores/probabilities of each cell mapping to all tissue locations, so you can select the ones you want to study further and see where they have mapped to.

**Comment by Hsu-Che-Wei** [comment]
Got it. Thank you very much.
