### ISSUE TITLE
output problem 

### ISSUE THREAD

**Issue by caiquanyou** [rajewsky-lab/novosparc#44]
Hi:
I use the scDATA(31053genes x 1638cells) as input,and the location grid shape is (ndarray(4060,2));
but I get the output cost_expression(ndarray(31053,31053)) and cost_location(ndarray(4060,4060));
how could I use the output or maybe I run it wrong??
Best!

**Comment by MalteMederacke** [comment]
I guess, you didnt transpose your scDATA, it needs to be in the format cells x genes. Maybe your input data had the right shape and you transposed it anyways or you forgot to do it.

**Comment by caiquanyou** [comment]
and another question : when I use 
location = create_target_space_from_image("10x/2.png")
return error like below:
<input>:10: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 9, in create_target_space_from_image
  File "<input>", line 10, in <listcomp>
TypeError: 'bool' object is not iterable

**Comment by phantom323** [comment]
I met the same error, and I change the codes:
img = imread(tissue_path)
img_width = img.shape[1]
img_height = img.shape[0]
locations = np.array([(x, y) for x in range(img_width) for y in range(img_height) if sum(img[y, x, :] == np.array([0, 0, 0, 0]))])
Then, the problem have been solved.
