### ISSUE TITLE
Display of ubiquitous genes

### ISSUE THREAD

**Issue by MalteMederacke** [rajewsky-lab/novosparc#47]
Hi, 

sorry to bother again. I have a question regarding the reconstruction or rather the display of ubiquitous expressed genes. For now, plotting the genes on default just takes the viridiris color scheme and scales it from the lowest value in the sdge to the highest. This is perfectly reasonable for patterned genes. To increase comparability I did Z-score normalization of the matrix, again, this works fine spatially resolved genes. 
But this seems to be problematic for genes which are expressed in a lot of cells, with seemingly random, low variation or in other cases in a gradient, but still present in most cells. If then plotted, it looks like either the pattern is biased towards random cells (random cells are 'yellow' with some background) or it is biased towards the part of the gradient with higher expression. What could be a way to display these genes similar to their appearance in FISH   (mostly homogeneous staining). Maybe something scaled by dispersion?

**Comment by nukappa** [comment]
Hi MalteMederacke, 
this can be indeed a problem for ubiquitous genes, as it might show artifacts as you describe.
For those genes, I like to plot their expression in the tSNE/UMAP space along with the spatial reconstruction, to showcase that they are indeed ubiquitous and that the spatial plotting might show artifacts.
We haven't really explored this further, but scaling by dispersion or similar as you suggest might do the trick.
