### ISSUE TITLE
error when running tissue.setup_reconstruction

### ISSUE THREAD

**Issue by shermas** [rajewsky-lab/novosparc#60]
Hey,

I'm working on incorporating my FISH data as an atlas to the novosparc pipeline.
I ran the following command with all of the variables already defined:

tissue.setup_reconstruction(atlas_matrix=atlas_matrix, 
                            markers_to_use=markers_to_use, 
                            num_neighbors_s=num_neighbors_s, 
                            num_neighbors_t=num_neighbors_t)

The error I get is the following:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_24120/2432922367.py in <module>
     12                             markers_to_use=markers_to_use,
     13                             num_neighbors_s=num_neighbors_s,
---> 14                             num_neighbors_t=num_neighbors_t)
     15 
     16 # alternative 2: handling each assumption separately

~\AppData\Local\Continuum\anaconda2\envs\novosparc\lib\site-packages\novosparc\common\_tissue.py in setup_reconstruction(self, markers_to_use, atlas_matrix, num_neighbors_s, num_neighbors_t, verbose)
     99                 # calculate cost matrices for OT
    100                 if self.markers_to_use is not None:
--> 101                         self.setup_linear_cost(self.markers_to_use, self.atlas_matrix)
    102                 self.setup_smooth_costs(num_neighbors_s=num_neighbors_s, num_neighbors_t=num_neighbors_t,verbose=verbose)
    103 

~\AppData\Local\Continuum\anaconda2\envs\novosparc\lib\site-packages\novosparc\common\_tissue.py in setup_linear_cost(self, markers_to_use, atlas_matrix, markers_metric, markers_metric_p)
     82                 atlas_expression = self.atlas_matrix / np.amax(self.atlas_matrix)
     83 
---> 84                 self.costs['markers'] = cdist(cell_expression, atlas_expression, metric=markers_metric, p=markers_metric_p)
     85                 self.num_markers = len(self.markers_to_use)
     86 

~\AppData\Local\Continuum\anaconda2\envs\novosparc\lib\site-packages\scipy\spatial\distance.py in cdist(XA, XB, metric, out, **kwargs)
   2952         if metric_info is not None:
   2953             cdist_fn = metric_info.cdist_func
-> 2954             return cdist_fn(XA, XB, out=out, **kwargs)
   2955         elif mstr.startswith("test_"):
   2956             metric_info = _TEST_METRICS.get(mstr, None)

TypeError: cdist_euclidean(): incompatible function arguments. The following argument types are supported:
    1. (x: object, y: object, w: object = None, out: object = None) -> numpy.ndarray

Invoked with: array([[-0.00363354, -0.02231607,  0.00856705, -0.00795672, -0.07818033],
       [-0.00840124, -0.05157987, -0.01674311, -0.01042449,  0.02550236],
       [-0.0054095 ,  0.34223324, -0.0155145 , -0.00490947, -0.07199101],
       ...,
       [-0.00817236, -0.03716966, -0.03761401, -0.00432769,  0.08396331],
       [-0.00887152, -0.03862168,  0.4267373 , -0.00338438, -0.06649771],
       [-0.00534304, -0.02891653, -0.00711811, -0.00705233, -0.07524257]],
      dtype=float32), array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32); kwargs: out=None, p=2

Can you help me solve this?

Thanks,
Shachar

**Comment by enessenel** [comment]
Hi Shachar,

yes, there was a bug but now it is fixed. Could you please pull the latest version (v0.4.4) and try again?

thanks!
